### ISSUE TITLE
Thermostats show up as Entity but should be Device

### ISSUE THREAD

**Issue by grazmarks** [araines/homeassistant-thermoplus-ble#8]
Hi,

First I need to thank you for this great custom_integration. Exactly what I was looking for for my Brifta thermostats. They work like a charm with this integration.

Would it be possible for this to show up as device with the respective sensors: Temp, Humidity, Battery?

The use case is: I would like to track humidity in a graph like I track temperature on my dashboard. Maybe there is an option in home assistant which I haven't found.

Many thanks!

**Comment by araines** [comment]
I was planning to do this as a feature enhancement in the future, but it requires a fairly significant rework of the way the internals work to do it nicely, so I haven't gotten around to it.

However, the good news is that you can do what you want to do already!  The temperature is obviously the main state of the entity, so you already have full access to that.  But both the battery level and humidity are actually stored as attributes on the temperature sensor entity, along with signal strength.

Here is an example of the attributes:
```
mac: '9B:B0:00:00:02:60'
rssi: -81
battery: 2971
temperature: 19.62
humidity: 57.06
battery_level: 80
unit_of_measurement: °C
friendly_name: Bedroom
device_class: temperature
```

`mac` is the mac address of the device
`rssi` is the signal strength in dB
`battery` is the current voltage measured on the battery in mV
`tempearture` is the current temperature in °C
`humidity` is the current relative humidity level in %

By using a [template sensor](https://www.home-assistant.io/integrations/template/), you can actually create new sensors based on these attributes.  For example:

```
sensor:
  - platform: template
    sensors:
      bedroom_humidity:
        friendly_name: "Bedroom Humidity"
        value_template: "{{ state_attr('sensor.thermoplus_9B_B0_00_00_02_60', 'humidity') }}"
        unit_of_measurement: '%'
```

Voila - one humidity sensor!
